# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76a8becca1b68dc9268a93df8c6a6ce7694e1011c450e08e7e7e909cf3ebb690521402106a0ab182e3a7e742b220cefb77472207ba0f005bcdc0219da8373b4d

test:
  secret_key_base: 5b012f9ec4e2fe7211ba67046324d64d2e61119ec527509c8c08b7c0dcfb7cf7afdb9dc8ef1f14a905692eb64a641132ca2a59dc72b8f4c5312147890cf02336

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
